package:
  name: febio
  version: 0.2.1

source:
  git_url: https://github.com/siboles/pyFEBio.git
  git_rev: 0.2.1

requirements:
  build:
    - python
    - numpy
    - future

  run:
    - python
    - numpy
    - future

test:
  # Python imports
  imports:
    - febio

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/siboles/pyFEBio
  license: MIT
  summary: 'A Python API for FEBio'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
